spring.application.name=moneymanager
# Server Port
server.port=8080

# Direct TCP Port 1433 Connection (Bypasses instance lookup & UDP 1434)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MoneyManagerDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=bank_app_user
spring.datasource.password=SecurePassword123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Connection Pool (HikariCP)
spring.datasource.hikari.pool-name=MoneyManagerHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Logging
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7